name: Build and publish release

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches: [main]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run: npm ci
      - run: npm test

  build-app-windows:
    runs-on: windows-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Match tag to package version
        uses: geritol/match-tag-to-package-version@0.2.0
        with:
          TAG_PREFIX: v
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: install dependencies
        run: npm ci
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  publish-app-mac:
    runs-on: macos-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Match tag to package version
        uses: geritol/match-tag-to-package-version@0.2.0
        with:
          TAG_PREFIX: v
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: install dependencies
        run: npm ci
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
