name: Build and publish release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  build-to-gh-pages:
    runs-on: ubuntu-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm ci
      - name: Build web page
        run: npm run build-web
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  
  build-app-windows:
    runs-on: windows-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Replace version with tag
        run: |
          # from refs/tags/vX.Y.Z get X.Y.Z
          VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          PLACEHOLDER='"version": "0.0.0"'
          VERSION_FILE='package.json'
          # Grep to ensure the placeholder is there, cancel build if not
          grep "$PLACEHOLDER" "$VERSION_FILE"
          sed -i "s/$PLACEHOLDER/\"version\": \"${VERSION}\"/g" "$VERSION_FILE"
        shell: bash
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install dependencies
        run: npm ci
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish

  publish-app-mac:
    runs-on: macos-latest
    needs: run-tests
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v2
    - name: Replace version with tag
      run: |
        # from refs/tags/vX.Y.Z get X.Y.Z
        VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
        PLACEHOLDER='"version": "0.0.0"'
        VERSION_FILE='package.json'
        # Grep to ensure the placeholder is there, cancel build if not
        grep "$PLACEHOLDER" "$VERSION_FILE"
        sed -i "s/$PLACEHOLDER/\"version\": \"${VERSION}\"/g" "$VERSION_FILE"
      shell: bash
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: install dependencies
      run: npm ci
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run publish